# Generated by Django 3.1 on 2020-09-07 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
        ('books', '0002_auto_20200907_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ManyToManyField(blank=True, related_name='authors', to='author.Author'),
        ),
        migrations.AlterField(
            model_name='bookunit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_units', to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookunit',
            name='serial',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
