# Generated by Django 3.1 on 2020-09-07 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20200907_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookunit',
            name='borrowed',
            field=models.BooleanField(default=False),
        ),
    ]
