# Generated by Django 3.1 on 2020-09-07 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='person_gender',
        ),
        migrations.AddField(
            model_name='rental',
            name='person_type',
            field=models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('VI', 'Visitor')], default='ST', max_length=2),
        ),
    ]
