# Generated by Django 3.1 on 2020-09-07 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20200907_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
