# Generated by Django 3.1.1 on 2020-09-04 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_remove_person_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='username',
            field=models.CharField(default='ak', max_length=45),
        ),
    ]
