# Generated by Django 3.1 on 2020-09-04 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_person_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='username',
        ),
    ]
